name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make
      
    - name: Build Docker image using Makefile
      run: make docker
      
    - name: Push the Docker image to Docker Hub
      run: |
        docker push farheenmalik01/activity2:latest

    - name: List Docker images
      run: make images
      
    - name: Start the Docker container
      run: make start
      
    - name: List running containers
      run: make containers
